import type { PlatformDef } from '../../types';
import { veoParamsWithEnhance } from './commonParams';

export const apizzzPlatformDef: PlatformDef = {
  id: 'apizzz',
  name: 'Apizzz',
  defaultBaseUrl: 'https://apizzz.com',
  defaultEndpoints: {
    createVideo: '/v1/video/create',
    queryTask: '/v1/video/query',
  },
  defaultModel: 'veo_3_1-components-4K',
  models: [
    {
      id: 'veo_3_1-components-4K',
      platformId: 'apizzz',
      name: 'Veo 3.1 单图 4K',
      label: 'Veo 3.1 单图4K (￥1.19/次)',
      price: '￥1.19/次',
      modes: ['image'],
      apiFormat: 'openai',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['4k'], [8], 8),
    },
    {
      id: 'veo_3_1-4K',
      platformId: 'apizzz',
      name: 'Veo 3.1 首尾帧 4K',
      label: 'Veo 3.1 首尾帧4K (￥1.19/次)',
      price: '￥1.19/次',
      modes: ['imageTail'],
      apiFormat: 'openai',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['4k'], [8], 8),
    },
    {
      id: 'veo_3_1-fast-4K',
      platformId: 'apizzz',
      name: 'Veo 3.1 Fast 首尾帧/文生 4K',
      label: 'Veo 3.1 Fast 文生/首尾帧4K (￥0.60/次)',
      price: '￥0.60/次',
      modes: ['text', 'imageTail'],
      apiFormat: 'openai',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['4k'], [8], 8),
    },
    {
      id: 'veo_3_1-fast-components-4K',
      platformId: 'apizzz',
      name: 'Veo 3.1 Fast 多图 4K',
      label: 'Veo 3.1 Fast 多图4K (￥1.20/次)',
      price: '￥1.20/次',
      modes: ['multiImage'],
      apiFormat: 'openai',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['4k'], [8], 8),
    },
    {
      id: 'veo_3_1-fast',
      platformId: 'apizzz',
      name: 'Veo 3.1 Fast 文生/首尾帧',
      label: 'Veo 3.1 Fast 文生/首尾帧 (￥0.60/次)',
      price: '￥0.60/次',
      modes: ['text', 'imageTail'],
      apiFormat: 'openai',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p', '4k'], [8], 8),
    },
    {
      id: 'veo3.1',
      platformId: 'apizzz',
      name: 'Veo 3.1 文生/首尾帧',
      label: 'Veo 3.1 文生/首尾帧 (￥0.98/次)',
      price: '￥0.98/次',
      modes: ['text', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p', '4k'], [8], 8),
    },
    {
      id: 'veo3.1-pro',
      platformId: 'apizzz',
      name: 'Veo 3.1 Pro 文生/首尾帧',
      label: 'Veo 3.1 Pro 文生/首尾帧 (￥4.90/次)',
      price: '￥4.90/次',
      modes: ['text', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p', '4k'], [8], 8),
    },
    {
      id: 'veo3.1-components',
      platformId: 'apizzz',
      name: 'Veo 3.1 参考图',
      label: 'Veo 3.1 参考图 (￥0.98/次)',
      price: '￥0.98/次',
      modes: ['multiImage'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p', '4k'], [8], 8),
    },
    {
      id: 'veo3.1-4k',
      platformId: 'apizzz',
      name: 'Veo 3.1 4K',
      label: 'Veo 3.1 4K (￥0.60/次)',
      price: '￥0.60/次',
      modes: ['text', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['4k'], [8], 8),
    },
    {
      id: 'veo3.1-pro-4k',
      platformId: 'apizzz',
      name: 'Veo 3.1 Pro 4K',
      label: 'Veo 3.1 Pro 4K (￥4.90/次)',
      price: '￥4.90/次',
      modes: ['text', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['4k'], [8], 8),
    },
    {
      id: 'veo3-fast',
      platformId: 'apizzz',
      name: 'Veo 3 Fast',
      label: 'Veo 3 Fast (文生/图生)',
      price: '',
      modes: ['text', 'image', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8),
    },
    {
      id: 'veo3',
      platformId: 'apizzz',
      name: 'Veo 3',
      label: 'Veo 3 (文生/图生)',
      price: '',
      modes: ['text', 'image', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8),
    },
    {
      id: 'veo3-fast-frames',
      platformId: 'apizzz',
      name: 'Veo 3 Fast 首帧',
      label: 'Veo 3 Fast 首帧',
      price: '',
      modes: ['image', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8),
    },
    {
      id: 'veo2-fast',
      platformId: 'apizzz',
      name: 'Veo 2 Fast',
      label: 'Veo 2 Fast (文生)',
      price: '',
      modes: ['text'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8),
    },
    {
      id: 'veo2',
      platformId: 'apizzz',
      name: 'Veo 2',
      label: 'Veo 2 (文生)',
      price: '',
      modes: ['text'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8),
    },
    {
      id: 'veo2-fast-frames',
      platformId: 'apizzz',
      name: 'Veo 2 Fast 首尾帧',
      label: 'Veo 2 Fast 首尾帧',
      price: '',
      modes: ['image', 'imageTail'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8, 2),
    },
    {
      id: 'veo2-fast-components',
      platformId: 'apizzz',
      name: 'Veo 2 Fast 多图',
      label: 'Veo 2 Fast 多图参考',
      price: '',
      modes: ['multiImage'],
      apiFormat: 'unified',
      params: veoParamsWithEnhance(['16:9', '9:16'], ['720p', '1080p'], [8], 8, 3),
    },
  ],
};
